version: '3'

services:
  gunicorn-server:
    build:
      context: .
      dockerfile: ./gunicorn/Dockerfile
    ports: 
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - celery-worker
  nginx-server:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./spotify_downloader/static:/usr/share/static/
    ports:
      - 80:80
  # python-run:
  #   build: 
  #     context: .
  #     dockerfile: ./run/Dockerfile
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - .:/usr/src/app
  redis:
    image: redis
    ports:
      - 6379:6379
  celery-worker:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    volumes: 
      - .:/usr/src/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - redis
