version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  celery-worker:
    build: .
    volumes: 
      - .:/usr/src/app
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    depends_on:
      - redis
